Traceback (most recent call last):
  File "/home/nrisse/anaconda3/envs/pyac3airborne/lib/python3.9/site-packages/jupyter_cache/executors/utils.py", line 51, in single_nb_execution
    executenb(
  File "/home/nrisse/anaconda3/envs/pyac3airborne/lib/python3.9/site-packages/nbclient/client.py", line 1112, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/home/nrisse/anaconda3/envs/pyac3airborne/lib/python3.9/site-packages/nbclient/util.py", line 74, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/home/nrisse/anaconda3/envs/pyac3airborne/lib/python3.9/site-packages/nbclient/util.py", line 53, in just_run
    return loop.run_until_complete(coro)
  File "/home/nrisse/anaconda3/envs/pyac3airborne/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/home/nrisse/anaconda3/envs/pyac3airborne/lib/python3.9/site-packages/nbclient/client.py", line 553, in async_execute
    await self.async_execute_cell(
  File "/home/nrisse/anaconda3/envs/pyac3airborne/lib/python3.9/site-packages/nbclient/client.py", line 857, in async_execute_cell
    self._check_raise_for_error(cell, exec_reply)
  File "/home/nrisse/anaconda3/envs/pyac3airborne/lib/python3.9/site-packages/nbclient/client.py", line 760, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
%pylab inline
import matplotlib.image as mpimg
img = mpimg.imread('map_MOSAiC-ACA_20200907.png')
fig, ax = plt.subplots(1, 1, figsize=(8, 8))
imgplot = ax.imshow(img)
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mFileNotFoundError[0m                         Traceback (most recent call last)
[0;32m<ipython-input-1-277a16903eaa>[0m in [0;36m<module>[0;34m[0m
[1;32m      1[0m [0mget_ipython[0m[0;34m([0m[0;34m)[0m[0;34m.[0m[0mrun_line_magic[0m[0;34m([0m[0;34m'pylab'[0m[0;34m,[0m [0;34m'inline'[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[1;32m      2[0m [0;32mimport[0m [0mmatplotlib[0m[0;34m.[0m[0mimage[0m [0;32mas[0m [0mmpimg[0m[0;34m[0m[0;34m[0m[0m
[0;32m----> 3[0;31m [0mimg[0m [0;34m=[0m [0mmpimg[0m[0;34m.[0m[0mimread[0m[0;34m([0m[0;34m'map_MOSAiC-ACA_20200907.png'[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m      4[0m [0mfig[0m[0;34m,[0m [0max[0m [0;34m=[0m [0mplt[0m[0;34m.[0m[0msubplots[0m[0;34m([0m[0;36m1[0m[0;34m,[0m [0;36m1[0m[0;34m,[0m [0mfigsize[0m[0;34m=[0m[0;34m([0m[0;36m8[0m[0;34m,[0m [0;36m8[0m[0;34m)[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[1;32m      5[0m [0mimgplot[0m [0;34m=[0m [0max[0m[0;34m.[0m[0mimshow[0m[0;34m([0m[0mimg[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m

[0;32m~/anaconda3/envs/pyac3airborne/lib/python3.9/site-packages/matplotlib/image.py[0m in [0;36mimread[0;34m(fname, format)[0m
[1;32m   1499[0m                     [0mresponse[0m [0;34m=[0m [0mio[0m[0;34m.[0m[0mBytesIO[0m[0;34m([0m[0mresponse[0m[0;34m.[0m[0mread[0m[0;34m([0m[0;34m)[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[1;32m   1500[0m                 [0;32mreturn[0m [0mimread[0m[0;34m([0m[0mresponse[0m[0;34m,[0m [0mformat[0m[0;34m=[0m[0mext[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0;32m-> 1501[0;31m     [0;32mwith[0m [0mimg_open[0m[0;34m([0m[0mfname[0m[0;34m)[0m [0;32mas[0m [0mimage[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m   1502[0m         return (_pil_png_to_float_array(image)
[1;32m   1503[0m                 [0;32mif[0m [0misinstance[0m[0;34m([0m[0mimage[0m[0;34m,[0m [0mPIL[0m[0;34m.[0m[0mPngImagePlugin[0m[0;34m.[0m[0mPngImageFile[0m[0;34m)[0m [0;32melse[0m[0;34m[0m[0;34m[0m[0m

[0;32m~/anaconda3/envs/pyac3airborne/lib/python3.9/site-packages/PIL/ImageFile.py[0m in [0;36m__init__[0;34m(self, fp, filename)[0m
[1;32m    107[0m         [0;32mif[0m [0misPath[0m[0;34m([0m[0mfp[0m[0;34m)[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[1;32m    108[0m             [0;31m# filename[0m[0;34m[0m[0;34m[0m[0;34m[0m[0m
[0;32m--> 109[0;31m             [0mself[0m[0;34m.[0m[0mfp[0m [0;34m=[0m [0mopen[0m[0;34m([0m[0mfp[0m[0;34m,[0m [0;34m"rb"[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m    110[0m             [0mself[0m[0;34m.[0m[0mfilename[0m [0;34m=[0m [0mfp[0m[0;34m[0m[0;34m[0m[0m
[1;32m    111[0m             [0mself[0m[0;34m.[0m[0m_exclusive_fp[0m [0;34m=[0m [0;32mTrue[0m[0;34m[0m[0;34m[0m[0m

[0;31mFileNotFoundError[0m: [Errno 2] No such file or directory: 'map_MOSAiC-ACA_20200907.png'
FileNotFoundError: [Errno 2] No such file or directory: 'map_MOSAiC-ACA_20200907.png'

