Traceback (most recent call last):
  File "/home/mech/.local/lib/python3.10/site-packages/jupyter_cache/executors/utils.py", line 51, in single_nb_execution
    executenb(
  File "/usr/lib/python3/dist-packages/nbclient/client.py", line 1093, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/usr/lib/python3/dist-packages/nbclient/util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/usr/lib/python3/dist-packages/nbclient/util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "/usr/lib/python3.10/asyncio/base_events.py", line 646, in run_until_complete
    return future.result()
  File "/usr/lib/python3/dist-packages/nbclient/client.py", line 559, in async_execute
    await self.async_execute_cell(
  File "/usr/lib/python3/dist-packages/nbclient/client.py", line 854, in async_execute_cell
    self._check_raise_for_error(cell, exec_reply)
  File "/usr/lib/python3/dist-packages/nbclient/client.py", line 756, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
fig, (ax1, ax2, ax3) = plt.subplots(3, 1, sharex=True, gridspec_kw=dict(height_ratios=(1, 1, 0.1)))

kwargs = dict(s=10, linewidths=0)
colors = cm.get_cmap('viridis', 6).colors
for i in range(0, 6):
    ax1.scatter(ds_mirac_p_sel.time, ds_mirac_p_sel.tb.sel(channel=i), label='%g GHz'%ds_mirac_p_sel.frequency.sel(channel=i).item(), color=colors[i], **kwargs)

for i in range(6, 8):
    ax2.scatter(ds_mirac_p_sel.time, ds_mirac_p_sel.tb.sel(channel=i), label='%g GHz'%ds_mirac_p_sel.frequency.sel(channel=i).item(), **kwargs)

ax1.legend(frameon=False, bbox_to_anchor=(1.05, 0.5), loc='center left')
ax2.legend(frameon=False, bbox_to_anchor=(1.05, 0.5), loc='center left')

ax1.set_ylabel('$T_b$ [K]')
ax2.set_ylabel('$T_b$ [K]')

# plot AMSR2 sea ice concentration
im = ax3.pcolormesh(np.array([ds_sea_ice.time, ds_sea_ice.time]),
               np.array([0, 1]),
               np.array([ds_sea_ice.sic]), cmap='Blues_r', vmin=0, vmax=100,
               shading='auto')
cax = fig.add_axes([0.87, 0.085, 0.1, ax3.get_position().height])
fig.colorbar(im, cax=cax, orientation='horizontal', label='Sea ice [%]')
ax3.tick_params(axis='y', labelleft=False, left=False)


ax3.set_xlabel('Time (hh:mm) [UTC]')
ax3.xaxis.set_major_formatter(mdates.DateFormatter('%H:%M'))

plt.show()
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mTypeError[0m                                 Traceback (most recent call last)
[0;32m/tmp/ipykernel_291840/1483793621.py[0m in [0;36m<module>[0;34m[0m
[1;32m     16[0m [0;34m[0m[0m
[1;32m     17[0m [0;31m# plot AMSR2 sea ice concentration[0m[0;34m[0m[0;34m[0m[0m
[0;32m---> 18[0;31m im = ax3.pcolormesh(np.array([ds_sea_ice.time, ds_sea_ice.time]),
[0m[1;32m     19[0m                [0mnp[0m[0;34m.[0m[0marray[0m[0;34m([0m[0;34m[[0m[0;36m0[0m[0;34m,[0m [0;36m1[0m[0;34m][0m[0;34m)[0m[0;34m,[0m[0;34m[0m[0;34m[0m[0m
[1;32m     20[0m                [0mnp[0m[0;34m.[0m[0marray[0m[0;34m([0m[0;34m[[0m[0mds_sea_ice[0m[0;34m.[0m[0msic[0m[0;34m][0m[0;34m)[0m[0;34m,[0m [0mcmap[0m[0;34m=[0m[0;34m'Blues_r'[0m[0;34m,[0m [0mvmin[0m[0;34m=[0m[0;36m0[0m[0;34m,[0m [0mvmax[0m[0;34m=[0m[0;36m100[0m[0;34m,[0m[0;34m[0m[0;34m[0m[0m

[0;32m/usr/lib/python3/dist-packages/matplotlib/__init__.py[0m in [0;36minner[0;34m(ax, data, *args, **kwargs)[0m
[1;32m   1414[0m     [0;32mdef[0m [0minner[0m[0;34m([0m[0max[0m[0;34m,[0m [0;34m*[0m[0margs[0m[0;34m,[0m [0mdata[0m[0;34m=[0m[0;32mNone[0m[0;34m,[0m [0;34m**[0m[0mkwargs[0m[0;34m)[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[1;32m   1415[0m         [0;32mif[0m [0mdata[0m [0;32mis[0m [0;32mNone[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[0;32m-> 1416[0;31m             [0;32mreturn[0m [0mfunc[0m[0;34m([0m[0max[0m[0;34m,[0m [0;34m*[0m[0mmap[0m[0;34m([0m[0msanitize_sequence[0m[0;34m,[0m [0margs[0m[0;34m)[0m[0;34m,[0m [0;34m**[0m[0mkwargs[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m   1417[0m [0;34m[0m[0m
[1;32m   1418[0m         [0mbound[0m [0;34m=[0m [0mnew_sig[0m[0;34m.[0m[0mbind[0m[0;34m([0m[0max[0m[0;34m,[0m [0;34m*[0m[0margs[0m[0;34m,[0m [0;34m**[0m[0mkwargs[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m

[0;32m/usr/lib/python3/dist-packages/matplotlib/axes/_axes.py[0m in [0;36mpcolormesh[0;34m(self, alpha, norm, cmap, vmin, vmax, shading, antialiased, *args, **kwargs)[0m
[1;32m   6060[0m         [0mkwargs[0m[0;34m.[0m[0msetdefault[0m[0;34m([0m[0;34m'edgecolors'[0m[0;34m,[0m [0;34m'none'[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[1;32m   6061[0m [0;34m[0m[0m
[0;32m-> 6062[0;31m         X, Y, C, shading = self._pcolorargs('pcolormesh', *args,
[0m[1;32m   6063[0m                                             shading=shading, kwargs=kwargs)
[1;32m   6064[0m         [0mcoords[0m [0;34m=[0m [0mnp[0m[0;34m.[0m[0mstack[0m[0;34m([0m[0;34m[[0m[0mX[0m[0;34m,[0m [0mY[0m[0;34m][0m[0;34m,[0m [0maxis[0m[0;34m=[0m[0;34m-[0m[0;36m1[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m

[0;32m/usr/lib/python3/dist-packages/matplotlib/axes/_axes.py[0m in [0;36m_pcolorargs[0;34m(self, funcname, shading, *args, **kwargs)[0m
[1;32m   5573[0m         [0;32mif[0m [0mshading[0m [0;34m==[0m [0;34m'flat'[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[1;32m   5574[0m             [0;32mif[0m [0;34m([0m[0mNx[0m[0;34m,[0m [0mNy[0m[0;34m)[0m [0;34m!=[0m [0;34m([0m[0mncols[0m [0;34m+[0m [0;36m1[0m[0;34m,[0m [0mnrows[0m [0;34m+[0m [0;36m1[0m[0;34m)[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[0;32m-> 5575[0;31m                 raise TypeError('Dimensions of C %s are incompatible with'
[0m[1;32m   5576[0m                                 ' X (%d) and/or Y (%d); see help(%s)' % (
[1;32m   5577[0m                                     C.shape, Nx, Ny, funcname))

[0;31mTypeError[0m: Dimensions of C (1, 1310) are incompatible with X (1310) and/or Y (2); see help(pcolormesh)
TypeError: Dimensions of C (1, 1310) are incompatible with X (1310) and/or Y (2); see help(pcolormesh)

